// Copyright 2026 https://yuewu.dev/en  All Rights Reserved.

#include "SettingsUI/GSS_GameSettingsMenu.h"

#include "Settings/GSS_GameSettingCollection.h"
#include "Settings/GSS_GameSettingValue.h"
#include "Settings/GSS_GameSettingRegistry.h"
#include "Settings/GSS_GameSettingsSubsystem.h"
#include "SettingsUI/GSS_GameSettingsPanel.h"
#include "Input/CommonUIInputTypes.h"
#include "GameplayTagsManager.h"

#include UE_INLINE_GENERATED_CPP_BY_NAME(GSS_GameSettingsMenu)

void UGSS_GameSettingsMenu::SetSettingsSubsystem(UGSS_GameSettingsSubsystem* InSubsystem)
{
	UnbindSubsystemEvents();
	SettingsSubsystem = InSubsystem;
	BindSubsystemEvents();
	if (Settings_Panel)
	{
		Settings_Panel->SetRegistry(SettingsSubsystem ? SettingsSubsystem->GetRegistry() : nullptr);
	}
	RebuildTopSettingsTabs();
	UpdateDirtyState();
}

void UGSS_GameSettingsMenu::NativeOnInitialized()
{
	Super::NativeOnInitialized();

	if (!BackInputActionData.IsNull())
	{
		BackHandle = RegisterUIActionBinding(FBindUIActionArgs(BackInputActionData, true, FSimpleDelegate::CreateUObject(this, &ThisClass::HandleBackAction)));
	}
	if (!ApplyInputActionData.IsNull())
	{
		ApplyHandle = RegisterUIActionBinding(FBindUIActionArgs(ApplyInputActionData, true, FSimpleDelegate::CreateUObject(this, &ThisClass::HandleApplyAction)));
		RemoveActionBinding(ApplyHandle);
	}
	if (!CancelChangesInputActionData.IsNull())
	{
		CancelChangesHandle = RegisterUIActionBinding(FBindUIActionArgs(CancelChangesInputActionData, true, FSimpleDelegate::CreateUObject(this, &ThisClass::HandleCancelChangesAction)));
		RemoveActionBinding(CancelChangesHandle);
	}
}

void UGSS_GameSettingsMenu::NativeOnActivated()
{
	Super::NativeOnActivated();
	if (!SettingsSubsystem)
	{
		SettingsSubsystem = UGSS_GameSettingsSubsystem::Get(GetOwningLocalPlayer());
	}
	BindSubsystemEvents();
	if (Settings_Panel)
	{
		Settings_Panel->SetRegistry(SettingsSubsystem ? SettingsSubsystem->GetRegistry() : nullptr);
	}
	BindTopSettingsTabs();
	RebuildTopSettingsTabs();
	UpdateDirtyState();
}

void UGSS_GameSettingsMenu::NativeOnDeactivated()
{
	UnbindTopSettingsTabs();
	UnbindSubsystemEvents();
	Super::NativeOnDeactivated();
}

void UGSS_GameSettingsMenu::NativeDestruct()
{
	UnbindTopSettingsTabs();
	ClearAutoGeneratedTopSettingsTabs();
	Super::NativeDestruct();
}

UWidget* UGSS_GameSettingsMenu::NativeGetDesiredFocusTarget() const
{
	if (UWidget* Target = BP_GetDesiredFocusTarget())
	{
		return Target;
	}
	return Settings_Panel;
}

void UGSS_GameSettingsMenu::ApplyChanges()
{
	if (SettingsSubsystem)
	{
		SettingsSubsystem->ApplyChanges();
	}
	UpdateDirtyState();
}

void UGSS_GameSettingsMenu::CancelChanges()
{
	if (SettingsSubsystem)
	{
		SettingsSubsystem->CancelChanges();
	}
	UpdateDirtyState();
}

bool UGSS_GameSettingsMenu::HaveSettingsBeenChanged() const
{
	return SettingsSubsystem && SettingsSubsystem->HavePendingChanges();
}

void UGSS_GameSettingsMenu::ResetVisibleSettingsToDefault()
{
	if (!Settings_Panel)
	{
		return;
	}

	for (UGSS_GameSetting* Setting : Settings_Panel->GetSettingsWeCanResetToDefault())
	{
		if (UGSS_GameSettingValue* Value = Cast<UGSS_GameSettingValue>(Setting))
		{
			if (Value->GetEditState().IsResettable())
			{
				Value->ResetToDefault();
			}
		}
	}
}

bool UGSS_GameSettingsMenu::AttemptToPopNavigation()
{
	if (Settings_Panel && Settings_Panel->CanPopNavigationStack())
	{
		Settings_Panel->PopNavigationStack();
		return true;
	}
	return false;
}

bool UGSS_GameSettingsMenu::NativeOnHandleBackAction()
{
	if (AttemptToPopNavigation())
	{
		return true;
	}
	return Super::NativeOnHandleBackAction();
}

UGSS_GameSettingCollection* UGSS_GameSettingsMenu::GetSettingCollection(FGameplayTag SettingId, bool& bHasAnySettings) const
{
	bHasAnySettings = false;
	UGSS_GameSettingCollection* Collection = SettingsSubsystem && SettingsSubsystem->GetRegistry()
		? Cast<UGSS_GameSettingCollection>(SettingsSubsystem->GetRegistry()->FindSettingById(SettingId))
		: nullptr;
	if (Collection)
	{
		FGSS_GameSettingFilterState FilterState;
		TArray<UGSS_GameSetting*> Settings;
		Collection->GetSettingsForFilter(FilterState, Settings);
		bHasAnySettings = !Settings.IsEmpty();
	}
	return Collection;
}

void UGSS_GameSettingsMenu::NavigateToSetting(FGameplayTag SettingId)
{
	NavigateToSettings({SettingId});
}

bool UGSS_GameSettingsMenu::NavigateToSettingByName(FName SettingName)
{
	if (SettingName.IsNone())
	{
		return false;
	}

	const FGameplayTag SettingId = UGameplayTagsManager::Get().RequestGameplayTag(SettingName, false);
	if (!SettingId.IsValid() || !SettingsSubsystem || !SettingsSubsystem->GetRegistry() || !SettingsSubsystem->GetRegistry()->FindSettingById(SettingId))
	{
		return false;
	}

	NavigateToSetting(SettingId);
	return true;
}

void UGSS_GameSettingsMenu::NavigateToSettings(const TArray<FGameplayTag>& SettingIds)
{
	if (!Settings_Panel || !SettingsSubsystem || !SettingsSubsystem->GetRegistry())
	{
		return;
	}

	FGSS_GameSettingFilterState FilterState;
	for (const FGameplayTag& SettingId : SettingIds)
	{
		if (UGSS_GameSetting* Setting = SettingsSubsystem->GetRegistry()->FindSettingById(SettingId))
		{
			FilterState.AddSettingToRootList(Setting);
		}
	}
	Settings_Panel->SetFilterState(FilterState);
}

bool UGSS_GameSettingsMenu::RebuildTopSettingsTabs()
{
	ClearAutoGeneratedTopSettingsTabs();
	if (!bAutoBuildTopSettingsTabs || !TopSettingsTabs || TopSettingsTabButtonType.IsNull() || !SettingsSubsystem)
	{
		return false;
	}

	UGSS_GameSettingRegistry* Registry = SettingsSubsystem->GetRegistry();
	if (!Registry)
	{
		return false;
	}

	for (UGSS_GameSettingCollection* Collection : Registry->GetTopLevelSettingCollections())
	{
		if (!Collection || !Collection->GetSettingId().IsValid())
		{
			continue;
		}

		if (!Collection->GetEditState().IsVisible())
		{
			continue;
		}

		FGSS_GameSettingFilterState FilterState;
		TArray<UGSS_GameSetting*> VisibleSettings;
		Collection->GetSettingsForFilter(FilterState, VisibleSettings);
		if (VisibleSettings.IsEmpty())
		{
			continue;
		}

		FGUIS_TabDescriptor TabDescriptor;
		TabDescriptor.TabId = Collection->GetSettingId().GetTagName();
		TabDescriptor.TabText = Collection->GetDisplayName();
		TabDescriptor.TabButtonType = TopSettingsTabButtonType;
		if (TopSettingsTabs->RegisterDynamicTab(TabDescriptor))
		{
			AutoGeneratedTopSettingsTabIds.Add(TabDescriptor.TabId);
		}
	}

	if (!AutoGeneratedTopSettingsTabIds.IsEmpty())
	{
		TopSettingsTabs->SelectTabByID(AutoGeneratedTopSettingsTabIds[0]);
	}
	return !AutoGeneratedTopSettingsTabIds.IsEmpty();
}

void UGSS_GameSettingsMenu::HandleBackAction()
{
	if (!AttemptToPopNavigation())
	{
		if (bApplyChangesOnBack)
		{
			ApplyChanges();
		}
		DeactivateWidget();
	}
}

void UGSS_GameSettingsMenu::HandleApplyAction()
{
	ApplyChanges();
}

void UGSS_GameSettingsMenu::HandleCancelChangesAction()
{
	CancelChanges();
}

void UGSS_GameSettingsMenu::HandleTopSettingsTabSelected(FName TabId)
{
	if (bAutoBuildTopSettingsTabs && AutoGeneratedTopSettingsTabIds.Contains(TabId))
	{
		NavigateToSettingByName(TabId);
	}
}

void UGSS_GameSettingsMenu::HandleSettingChanged(FGameplayTag, UGSS_GameSetting*, EGSS_GameSettingChangeReason)
{
	UpdateDirtyState();
}

void UGSS_GameSettingsMenu::HandleSettingApplied(FGameplayTag, UGSS_GameSetting*)
{
	UpdateDirtyState();
}

void UGSS_GameSettingsMenu::UpdateDirtyState()
{
	const bool bSettingsDirty = HaveSettingsBeenChanged();
	if (ApplyHandle.IsValid())
	{
		if (bSettingsDirty && !GetActionBindings().Contains(ApplyHandle))
		{
			AddActionBinding(ApplyHandle);
		}
		else if (!bSettingsDirty && GetActionBindings().Contains(ApplyHandle))
		{
			RemoveActionBinding(ApplyHandle);
		}
	}
	if (CancelChangesHandle.IsValid())
	{
		if (bSettingsDirty && !GetActionBindings().Contains(CancelChangesHandle))
		{
			AddActionBinding(CancelChangesHandle);
		}
		else if (!bSettingsDirty && GetActionBindings().Contains(CancelChangesHandle))
		{
			RemoveActionBinding(CancelChangesHandle);
		}
	}
	OnSettingsDirtyStateChanged(bSettingsDirty);
}

void UGSS_GameSettingsMenu::BindSubsystemEvents()
{
	if (SettingsSubsystem)
	{
		SettingsSubsystem->OnSettingPendingChanged.AddDynamic(this, &ThisClass::HandleSettingChanged);
		SettingsSubsystem->OnSettingApplied.AddDynamic(this, &ThisClass::HandleSettingApplied);
	}
}

void UGSS_GameSettingsMenu::UnbindSubsystemEvents()
{
	if (SettingsSubsystem)
	{
		SettingsSubsystem->OnSettingPendingChanged.RemoveDynamic(this, &ThisClass::HandleSettingChanged);
		SettingsSubsystem->OnSettingApplied.RemoveDynamic(this, &ThisClass::HandleSettingApplied);
	}
}

void UGSS_GameSettingsMenu::BindTopSettingsTabs()
{
	if (bAutoBuildTopSettingsTabs && TopSettingsTabs)
	{
		TopSettingsTabs->OnTabSelected.RemoveDynamic(this, &ThisClass::HandleTopSettingsTabSelected);
		TopSettingsTabs->OnTabSelected.AddDynamic(this, &ThisClass::HandleTopSettingsTabSelected);
	}
}

void UGSS_GameSettingsMenu::UnbindTopSettingsTabs()
{
	if (TopSettingsTabs)
	{
		TopSettingsTabs->OnTabSelected.RemoveDynamic(this, &ThisClass::HandleTopSettingsTabSelected);
	}
}

void UGSS_GameSettingsMenu::ClearAutoGeneratedTopSettingsTabs()
{
	if (TopSettingsTabs)
	{
		for (const FName TabId : AutoGeneratedTopSettingsTabIds)
		{
			TopSettingsTabs->RemoveTab(TabId);
		}
	}
	AutoGeneratedTopSettingsTabIds.Reset();
}
