// Copyright 2026 https://yuewu.dev/en  All Rights Reserved.

#include "SettingsUI/GSS_SettingsScreen.h"

#include "Settings/GSS_GameSettingAction.h"
#include "Settings/GSS_GameSettingCollection.h"
#include "Settings/GSS_GameSettingRegistry.h"
#include "Settings/GSS_SettingsSubsystem.h"
#include "SettingsUI/GSS_SettingsPanel.h"
#include "Input/CommonUIInputTypes.h"
#include "GameplayTagsManager.h"

#include UE_INLINE_GENERATED_CPP_BY_NAME(GSS_SettingsScreen)

void UGSS_SettingsScreen::SetSettingsSubsystem(UGSS_SettingsSubsystem* InSubsystem)
{
	UnbindSubsystemEvents();
	SettingsSubsystem = InSubsystem;
	BindSubsystemEvents();
	if (Settings_Panel)
	{
		Settings_Panel->SetSettingsSubsystem(SettingsSubsystem);
	}
	RebuildTopSettingsTabs();
	UpdateDirtyState();
}

void UGSS_SettingsScreen::NativeOnInitialized()
{
	Super::NativeOnInitialized();

	if (!BackInputActionData.IsNull())
	{
		BackHandle = RegisterUIActionBinding(FBindUIActionArgs(BackInputActionData, true, FSimpleDelegate::CreateUObject(this, &ThisClass::HandleBackAction)));
	}
	if (!ApplyInputActionData.IsNull())
	{
		ApplyHandle = RegisterUIActionBinding(FBindUIActionArgs(ApplyInputActionData, true, FSimpleDelegate::CreateUObject(this, &ThisClass::HandleApplyAction)));
		RemoveActionBinding(ApplyHandle);
	}
	if (!CancelChangesInputActionData.IsNull())
	{
		CancelChangesHandle = RegisterUIActionBinding(FBindUIActionArgs(CancelChangesInputActionData, true, FSimpleDelegate::CreateUObject(this, &ThisClass::HandleCancelChangesAction)));
		RemoveActionBinding(CancelChangesHandle);
	}
}

void UGSS_SettingsScreen::NativeOnActivated()
{
	Super::NativeOnActivated();
	if (!SettingsSubsystem)
	{
		SettingsSubsystem = UGSS_SettingsSubsystem::Get(GetOwningLocalPlayer());
	}
	BindSubsystemEvents();
	if (Settings_Panel)
	{
		Settings_Panel->SetSettingsSubsystem(SettingsSubsystem);
	}
	BindTopSettingsTabs();
	RebuildTopSettingsTabs();
	UpdateDirtyState();
}

void UGSS_SettingsScreen::NativeOnDeactivated()
{
	UnbindTopSettingsTabs();
	UnbindSubsystemEvents();
	Super::NativeOnDeactivated();
}

void UGSS_SettingsScreen::NativeDestruct()
{
	UnbindTopSettingsTabs();
	ClearAutoGeneratedTopSettingsTabs();
	Super::NativeDestruct();
}

UWidget* UGSS_SettingsScreen::NativeGetDesiredFocusTarget() const
{
	if (UWidget* Target = BP_GetDesiredFocusTarget())
	{
		return Target;
	}
	return Settings_Panel;
}

void UGSS_SettingsScreen::ApplyChanges()
{
	if (SettingsSubsystem)
	{
		SettingsSubsystem->ApplyChanges();
	}
	UpdateDirtyState();
}

void UGSS_SettingsScreen::CancelChanges()
{
	if (SettingsSubsystem)
	{
		SettingsSubsystem->CancelChanges();
	}
	UpdateDirtyState();
}

bool UGSS_SettingsScreen::HavePendingChanges() const
{
	return SettingsSubsystem && SettingsSubsystem->HavePendingChanges();
}

bool UGSS_SettingsScreen::AttemptToPopNavigation()
{
	return Settings_Panel && Settings_Panel->CanPopNavigation() && Settings_Panel->PopNavigation();
}

bool UGSS_SettingsScreen::NativeOnHandleBackAction()
{
	if (AttemptToPopNavigation())
	{
		return true;
	}
	return Super::NativeOnHandleBackAction();
}

UGSS_GameSettingCollection* UGSS_SettingsScreen::GetSettingCollection(FGameplayTag SettingId, bool& bHasAnySettings) const
{
	bHasAnySettings = false;
	UGSS_GameSettingCollection* Collection = SettingsSubsystem && SettingsSubsystem->GetRegistry()
		? Cast<UGSS_GameSettingCollection>(SettingsSubsystem->GetRegistry()->FindSettingById(SettingId))
		: nullptr;
	if (Collection)
	{
		FGSS_GameSettingFilterState FilterState;
		TArray<UGSS_GameSetting*> Settings;
		Collection->GetSettingsForFilter(FilterState, Settings);
		bHasAnySettings = !Settings.IsEmpty();
	}
	return Collection;
}

void UGSS_SettingsScreen::NavigateToSetting(FGameplayTag SettingId)
{
	NavigateToSettings({SettingId});
}

bool UGSS_SettingsScreen::NavigateToSettingByName(FName SettingName)
{
	if (SettingName.IsNone())
	{
		return false;
	}

	const FGameplayTag SettingId = UGameplayTagsManager::Get().RequestGameplayTag(SettingName, false);
	if (!SettingId.IsValid())
	{
		return false;
	}

	NavigateToSetting(SettingId);
	return true;
}

void UGSS_SettingsScreen::NavigateToSettings(const TArray<FGameplayTag>& SettingIds)
{
	if (!Settings_Panel || !SettingsSubsystem || !SettingsSubsystem->GetRegistry())
	{
		return;
	}

	FGSS_GameSettingFilterState FilterState;
	for (const FGameplayTag& SettingId : SettingIds)
	{
		if (UGSS_GameSetting* Setting = SettingsSubsystem->GetRegistry()->FindSettingById(SettingId))
		{
			FilterState.AddSettingToRootList(Setting);
		}
	}
	Settings_Panel->SetFilterState(FilterState);
}

bool UGSS_SettingsScreen::RebuildTopSettingsTabs()
{
	ClearAutoGeneratedTopSettingsTabs();
	if (!bAutoBuildTopSettingsTabs || !TopSettingsTabs || TopSettingsTabButtonType.IsNull() || !SettingsSubsystem)
	{
		return false;
	}

	UGSS_GameSettingRegistry* Registry = SettingsSubsystem->GetRegistry();
	if (!Registry)
	{
		return false;
	}

	for (UGSS_GameSettingCollection* Collection : Registry->GetTopLevelSettingCollections())
	{
		if (!Collection || !Collection->GetSettingId().IsValid())
		{
			continue;
		}

		const UGSS_SettingEditableState* EditState = Collection->GetEditState();
		if (EditState && !EditState->IsVisible())
		{
			continue;
		}

		FGSS_GameSettingFilterState FilterState;
		TArray<UGSS_GameSetting*> VisibleSettings;
		Collection->GetSettingsForFilter(FilterState, VisibleSettings);
		if (VisibleSettings.IsEmpty())
		{
			continue;
		}

		FGUIS_TabDescriptor TabDescriptor;
		TabDescriptor.TabId = Collection->GetSettingId().GetTagName();
		TabDescriptor.TabText = Collection->GetDisplayName();
		TabDescriptor.TabButtonType = TopSettingsTabButtonType;
		if (TopSettingsTabs->RegisterDynamicTab(TabDescriptor))
		{
			AutoGeneratedTopSettingsTabIds.Add(TabDescriptor.TabId);
		}
	}

	if (!AutoGeneratedTopSettingsTabIds.IsEmpty())
	{
		TopSettingsTabs->SelectTabByID(AutoGeneratedTopSettingsTabIds[0]);
	}
	return !AutoGeneratedTopSettingsTabIds.IsEmpty();
}

void UGSS_SettingsScreen::HandleBackAction()
{
	if (!AttemptToPopNavigation())
	{
		if (bApplyChangesOnBack)
		{
			ApplyChanges();
		}
		DeactivateWidget();
	}
}

void UGSS_SettingsScreen::HandleApplyAction()
{
	ApplyChanges();
}

void UGSS_SettingsScreen::HandleCancelChangesAction()
{
	CancelChanges();
}

void UGSS_SettingsScreen::HandleTopSettingsTabSelected(FName TabId)
{
	if (bAutoBuildTopSettingsTabs && AutoGeneratedTopSettingsTabIds.Contains(TabId))
	{
		NavigateToSettingByName(TabId);
	}
}

void UGSS_SettingsScreen::HandleSettingChanged(FGameplayTag, UGSS_GameSetting*, EGSS_GameSettingChangeReason)
{
	UpdateDirtyState();
}

void UGSS_SettingsScreen::UpdateDirtyState()
{
	const bool bSettingsDirty = HavePendingChanges();
	if (ApplyHandle.IsValid())
	{
		if (bSettingsDirty && !GetActionBindings().Contains(ApplyHandle))
		{
			AddActionBinding(ApplyHandle);
		}
		else if (!bSettingsDirty && GetActionBindings().Contains(ApplyHandle))
		{
			RemoveActionBinding(ApplyHandle);
		}
	}
	if (CancelChangesHandle.IsValid())
	{
		if (bSettingsDirty && !GetActionBindings().Contains(CancelChangesHandle))
		{
			AddActionBinding(CancelChangesHandle);
		}
		else if (!bSettingsDirty && GetActionBindings().Contains(CancelChangesHandle))
		{
			RemoveActionBinding(CancelChangesHandle);
		}
	}
	OnSettingsDirtyStateChanged(bSettingsDirty);
}

void UGSS_SettingsScreen::HandleSettingAction(FGameplayTag, UGSS_GameSetting* Setting)
{
	if (UGSS_GameSettingAction* Action = Cast<UGSS_GameSettingAction>(Setting))
	{
		IGSS_SettingsActionHandler::Execute_ExecuteSettingsAction(this, Action->GetNamedAction(), Action);
	}
}

void UGSS_SettingsScreen::BindSubsystemEvents()
{
	if (SettingsSubsystem)
	{
		SettingsSubsystem->OnSettingActionExecuted.AddDynamic(this, &ThisClass::HandleSettingAction);
		SettingsSubsystem->OnSettingPendingChanged.AddDynamic(this, &ThisClass::HandleSettingChanged);
	}
}

void UGSS_SettingsScreen::UnbindSubsystemEvents()
{
	if (SettingsSubsystem)
	{
		SettingsSubsystem->OnSettingActionExecuted.RemoveDynamic(this, &ThisClass::HandleSettingAction);
		SettingsSubsystem->OnSettingPendingChanged.RemoveDynamic(this, &ThisClass::HandleSettingChanged);
	}
}

void UGSS_SettingsScreen::BindTopSettingsTabs()
{
	if (bAutoBuildTopSettingsTabs && TopSettingsTabs)
	{
		TopSettingsTabs->OnTabSelected.RemoveDynamic(this, &ThisClass::HandleTopSettingsTabSelected);
		TopSettingsTabs->OnTabSelected.AddDynamic(this, &ThisClass::HandleTopSettingsTabSelected);
	}
}

void UGSS_SettingsScreen::UnbindTopSettingsTabs()
{
	if (TopSettingsTabs)
	{
		TopSettingsTabs->OnTabSelected.RemoveDynamic(this, &ThisClass::HandleTopSettingsTabSelected);
	}
}

void UGSS_SettingsScreen::ClearAutoGeneratedTopSettingsTabs()
{
	if (TopSettingsTabs)
	{
		for (const FName TabId : AutoGeneratedTopSettingsTabIds)
		{
			TopSettingsTabs->RemoveTab(TabId);
		}
	}
	AutoGeneratedTopSettingsTabIds.Reset();
}
