// Copyright 2026 https://yuewu.dev/en  All Rights Reserved.

#include "Settings/GSS_GameSetting.h"
#include "Framework/Text/ITextDecorator.h"
#include "Framework/Text/RichTextMarkupProcessing.h"
#include "Engine/LocalPlayer.h"
#include "HAL/IConsoleManager.h"

#include UE_INLINE_GENERATED_CPP_BY_NAME(GSS_GameSetting)

#define LOCTEXT_NAMESPACE "GSS_GameSetting"

#define UE_CAN_SHOW_SETTINGS_DEBUG_INFO (!UE_BUILD_SHIPPING)

namespace GSSSettingsConsoleVars
{
#if UE_CAN_SHOW_SETTINGS_DEBUG_INFO
	int32 ShowDebugInfoMode = -1;

	static FAutoConsoleVariableRef CVarGSSShowDebugInfo(
		TEXT("GSS.Settings.ShowDebugInfo"),
		ShowDebugInfoMode,
		TEXT("Should we show the developer name and class as part of dynamic details?\n")
		TEXT("  -1: Default (enabled in editor, disabled in -game or cooked builds)\n")
		TEXT("   0: Never show it\n")
		TEXT("   1: Always show it\n")
		TEXT("\n")
		TEXT("  Note: Shipping builds always disable this"),
		ECVF_Default);
#endif
}


//--------------------------------------
// UGSS_GameSetting
//--------------------------------------

void UGSS_GameSetting::Initialize(ULocalPlayer* InLocalPlayer)
{
	// If we've already gotten this local player we're already initialized.
	if (LocalPlayer == InLocalPlayer)
	{
		return;
	}

	LocalPlayer = InLocalPlayer;

	//TODO: GameSettings
	//LocalPlayer->OnPlayerLoggedIn().AddUObject(this, &UGSS_GameSetting::RefreshEditableState, true);

#if !UE_BUILD_SHIPPING
	ensureAlwaysMsgf(DevName != NAME_None, TEXT("You must provide a DevName for the setting."));
	ensureAlwaysMsgf(!DisplayName.IsEmpty(), TEXT("You must provide a DisplayName for settings."));
#endif

	for (UGSS_GameSettingEditCondition* EditCondition : EditConditions)
	{
		EditCondition->InitializeCondition(this);
	}

	// If there are any child settings go ahead and initialize them as well.
	for (UGSS_GameSetting* Setting : GetChildSettings())
	{
		Setting->Initialize(LocalPlayer);
	}

	Startup();
}

void UGSS_GameSetting::Startup()
{
	StartupComplete();
}

void UGSS_GameSetting::StartupComplete()
{
	ensureMsgf(!bReady, TEXT("StartupComplete called twice."));

	if (!bReady)
	{
		bReady = true;
		OnInitialized();
	}
}

void UGSS_GameSetting::Apply()
{
	OnApply();

	// Run through any edit conditions and let them know things changed.
	for (UGSS_GameSettingEditCondition* EditCondition : EditConditions)
	{
		EditCondition->OnSettingApplied();
	}

	OnSettingAppliedEvent.Broadcast(this);
}

void UGSS_GameSetting::OnInitialized()
{
	ensureMsgf(bReady, TEXT("OnInitialized called directly instead of via StartupComplete."));
	ComputeEditableState();
}

void UGSS_GameSetting::OnApply()
{
}

UWorld* UGSS_GameSetting::GetWorld() const
{
	return LocalPlayer ? LocalPlayer->GetWorld() : nullptr;
}

void UGSS_GameSetting::SetSettingParent(UGSS_GameSetting* InSettingParent)
{
	SettingParent = InSettingParent;
}

void UGSS_GameSetting::ComputeEditableState()
{
	EditableStateCache = FGSS_GameSettingEditableState();

	// Does this setting itself have any special rules?
	OnGatherEditState(EditableStateCache);

	// Run through any edit conditions
	for (UGSS_GameSettingEditCondition* EditCondition : EditConditions)
	{
		if (EditCondition)
		{
			EditCondition->Evaluate(EditableStateCache);
		}
	}
}

void UGSS_GameSetting::OnGatherEditState(FGSS_GameSettingEditableState& InOutEditState) const
{

}

const FString& UGSS_GameSetting::GetDescriptionPlainText() const
{
	RefreshPlainText();
	return AutoGenerated_DescriptionPlainText;
}

void UGSS_GameSetting::RefreshPlainText() const
{
	//TODO: GameSettings
	// TODO NDarnell Settings - Will need to recache if the language changes.

	if (bRefreshPlainSearchableText)
	{
		TArray<FTextLineParseResults> ActualResultsArray;
		FString ActualOutput;
		FDefaultRichTextMarkupParser::GetStaticInstance()->Process(ActualResultsArray, DescriptionRichText.ToString(), ActualOutput);

		AutoGenerated_DescriptionPlainText.Reset();
		for (const FTextLineParseResults& Line : ActualResultsArray)
		{
			for (const FTextRunParseResults& Run : Line.Runs)
			{
				if (Run.Name.IsEmpty())
				{
					AutoGenerated_DescriptionPlainText.Append(ActualOutput.Mid(Run.OriginalRange.BeginIndex, Run.OriginalRange.Len()));
				}
				else if (!Run.ContentRange.IsEmpty())
				{
					AutoGenerated_DescriptionPlainText.Append(ActualOutput.Mid(Run.ContentRange.BeginIndex, Run.ContentRange.Len()));
				}
			}
		}

		bRefreshPlainSearchableText = false;
	}
}

void UGSS_GameSetting::NotifySettingChanged(EGSS_GameSettingChangeReason Reason)
{
	OnSettingChanged(Reason);
	
	// Run through any edit conditions and let them know things changed.
	for (UGSS_GameSettingEditCondition* EditCondition : EditConditions)
	{
		if (EditCondition)
		{
			EditCondition->OnSettingValueChanged(Reason);
		}
	}

	if (!bOnSettingChangedEventGuard)
	{
		TGuardValue<bool> Guard(bOnSettingChangedEventGuard, true);
		OnSettingChangedEvent.Broadcast(this, Reason);
	}
}

void UGSS_GameSetting::OnSettingChanged(EGSS_GameSettingChangeReason Reason)
{
	// No-Op
}

void UGSS_GameSetting::AddEditCondition(UGSS_GameSettingEditCondition* InEditCondition)
{
	if (InEditCondition)
	{
		EditConditions.Add(InEditCondition);
		if (LocalPlayer)
		{
			InEditCondition->InitializeCondition(this);
		}
	}
}

void UGSS_GameSetting::AddEditDependency(UGSS_GameSetting* DependencySetting)
{
	if (ensure(DependencySetting))
	{
		DependencySetting->OnSettingChangedEvent.AddUObject(this, &ThisClass::HandleEditDependencyChanged);
		DependencySetting->OnSettingEditConditionChangedEvent.AddUObject(this, &ThisClass::HandleEditDependencyChanged);
	}
}

void UGSS_GameSetting::RefreshEditableState(bool bNotifyEditConditionsChanged)
{
	// The LocalPlayer may be destroyed out from under us, if that happens,
	// we need to ignore attempts to refresh the editable state.
	if (!LocalPlayer)
	{
		return;
	}

	//TODO: GameSettings
	//// We should wait until the player is fully logged in before trying to refresh settings.
	//if (!LocalPlayer->IsLoggedIn())
	//{
	//	return;
	//}

	if (!bOnEditConditionsChangedEventGuard)
	{
		TGuardValue<bool> Guard(bOnEditConditionsChangedEventGuard, true);
	
		ComputeEditableState();

		if (bNotifyEditConditionsChanged)
		{
			NotifyEditConditionsChanged();
		}		
	}
}

void UGSS_GameSetting::NotifyEditConditionsChanged()
{
	OnEditConditionsChanged();

	OnSettingEditConditionChangedEvent.Broadcast(this);
}

void UGSS_GameSetting::OnEditConditionsChanged()
{

}

void UGSS_GameSetting::HandleEditDependencyChanged(UGSS_GameSetting* DependencySetting)
{
	OnDependencyChanged();
	RefreshEditableState();
}

void UGSS_GameSetting::HandleEditDependencyChanged(UGSS_GameSetting* DependencySetting, EGSS_GameSettingChangeReason Reason)
{
	OnDependencyChanged();
	RefreshEditableState();

	if (Reason != EGSS_GameSettingChangeReason::DependencyChanged)
	{
		NotifySettingChanged(EGSS_GameSettingChangeReason::DependencyChanged);
	}
}

void UGSS_GameSetting::OnDependencyChanged()
{

}

FText UGSS_GameSetting::GetDynamicDetails() const
{
	if (!LocalPlayer)
	{
		return FText::GetEmpty();
	}

	FText DynamicDetailsText = DynamicDetails.IsBound() ? DynamicDetails.Execute(*LocalPlayer) : FText::GetEmpty();
	
#if UE_CAN_SHOW_SETTINGS_DEBUG_INFO
	if ((GSSSettingsConsoleVars::ShowDebugInfoMode == 1) || ((GSSSettingsConsoleVars::ShowDebugInfoMode == -1) && GIsEditor))
	{
		const FString DevSettingDetails = FString::Printf(TEXT("%s<debug>DevName: %s</>\n<debug>Class: %s</>"),
			DynamicDetailsText.IsEmpty() ? TEXT("") : TEXT("\n"),
			*DevName.ToString(),
			*GetClass()->GetName());

		DynamicDetailsText = FText::Format(LOCTEXT("DevDynamicDetailsFormat", "{0}{1}"),
			DynamicDetailsText,
			FText::FromString(DevSettingDetails));
	}
#endif

	return DynamicDetailsText;
}

FText UGSS_GameSetting::GetDynamicDetailsInternal() const
{
	return FText::GetEmpty();
}

UGSS_GameSetting::FStringCultureCache::FStringCultureCache(TFunction<FString()> InStringGetter)
	: Culture(FInternationalization::Get().GetCurrentCulture())
	, StringGetter(InStringGetter)
{
	StringCache = StringGetter();
}

void UGSS_GameSetting::FStringCultureCache::Invalidate()
{
	StringCache = StringGetter();
	Culture = FInternationalization::Get().GetCurrentCulture();
}

FString UGSS_GameSetting::FStringCultureCache::Get() const
{
	if (Culture == FInternationalization::Get().GetCurrentCulture())
	{
		return StringCache;
	}

	StringCache = StringGetter();
	Culture = FInternationalization::Get().GetCurrentCulture();

	return StringCache;
}

#undef LOCTEXT_NAMESPACE
