// Copyright 2024 https://yuewu.dev/en  All Rights Reserved.

#pragma once
#include "NativeGameplayTags.h"

namespace GUIS_GameModalActionTags
{
	GENERICUISYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ok);
	GENERICUISYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cancel);
	GENERICUISYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Yes);
	GENERICUISYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(No);
	GENERICUISYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unknown);
}

namespace GUIS_GameUILayerTags
{
	GENERICUISYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Modal);
}
