[CoreRedirects]
;Lyra context effect migrate.

;+ClassRedirects=(OldName="/Script/LyraGame.LyraContextEffectsLibrary",NewName="/Script/GenericMovementSystem.GMS_ContextEffectsLibrary")
;+ClassRedirects=(OldName="/Script/LyraGame.LyraContextEffectComponent",NewName="/Script/GenericMovementSystem.GMS_ContextEffectComponent")
;+ClassRedirects=(OldName="/Script/LyraGame.GMS_ContextEffectsInterface",NewName="/Script/GenericMovementSystem.GMS_ContextEffectsInterface")
;+EnumRedirects=(OldName="/Script/LyraGame.EEffectsContextMatchType",NewName="/Script/GenericMovementSystem.EGMS_EffectsContextMatchType")
;
;+ClassRedirects=(OldName="/Script/LyraGame.GMS_ContextEffectsInterface",NewName="/Script/GenericMovementSystem.GMS_ContextEffectsInterface")
;
;+ClassRedirects=(OldName="/Script/LyraGame.AnimNotify_LyraContextEffects",NewName="/Script/GenericMovementSystem.GMS_AnimNotify_ContextEffects")
;
;+StructRedirects=(OldName="/Script/LyraGame.LyraContextEffectAnimNotifyVFXSettings",NewName="/Script/GenericMovementSystem.GMS_ContextEffectAnimNotifyVFXSettings")
;+StructRedirects=(OldName="/Script/LyraGame.LyraContextEffectAnimNotifyAudioSettings",NewName="/Script/GenericMovementSystem.GMS_ContextEffectAnimNotifyAudioSettings")
;+StructRedirects=(OldName="/Script/LyraGame.LyraContextEffectAnimNotifyTraceSettings",NewName="/Script/GenericMovementSystem.GMS_ContextEffectAnimNotifyTraceSettings")
;+StructRedirects=(OldName="/Script/LyraGame.LyraContextEffectAnimNotifyPreviewSettings",NewName="/Script/GenericMovementSystem.GMS_ContextEffectAnimNotifyPreviewSettings")
;
;
;+EnumRedirects=(OldName="/Script/LyraGame.EContextEffectsLibraryLoadState",NewName="/Script/GenericMovementSystem.EGMS_ContextEffectsLibraryLoadState")
;+StructRedirects=(OldName="/Script/LyraGame.LyraContextEffects",NewName="/Script/GenericMovementSystem.GMS_ContextEffects")
;+ClassRedirects=(OldName="/Script/LyraGame.LyraActiveContextEffects",NewName="/Script/GenericMovementSystem.GMS_ActiveContextEffects")
;+ClassRedirects=(OldName="/Script/LyraGame.LyraContextEffectsSettings",NewName="/Script/GenericMovementSystem.GMS_ContextEffectsSettings")
;+ClassRedirects=(OldName="/Script/LyraGame.LyraContextEffectsSet",NewName="/Script/GenericMovementSystem.GMS_ContextEffectsSet")
;+PropertyRedirects=(OldName="/Script/LyraGame.GMS_ContextEffectsSet.LyraContextEffectsLibraries",NewName="/Script/GenericMovementSystem.GMS_ContextEffectsSet.ContextEffectsLibraries")


;GMS To GES migrate
+StructRedirects=(OldName="/Script/GenericMovementSystem.GMS_ContextEffectAnimNotifyVFXSettings",NewName="/Script/GenericEffectsSystem.GES_ContextEffectAnimNotifyVFXSettings")
+StructRedirects=(OldName="/Script/GenericMovementSystem.GMS_ContextEffectAnimNotifyAudioSettings",NewName="/Script/GenericEffectsSystem.GES_ContextEffectAnimNotifyAudioSettings")
+StructRedirects=(OldName="/Script/GenericMovementSystem.GMS_ContextEffectAnimNotifyTraceSettings",NewName="/Script/GenericEffectsSystem.GES_ContextEffectAnimNotifyTraceSettings")
+StructRedirects=(OldName="/Script/GenericMovementSystem.GMS_ContextEffectAnimNotifyPreviewSettings",NewName="/Script/GenericEffectsSystem.GES_ContextEffectAnimNotifyPreviewSettings")
+StructRedirects=(OldName="/Script/GenericMovementSystem.GMS_ContextEffects",NewName="/Script/GenericEffectsSystem.GES_ContextEffects")
+EnumRedirects=(OldName="/Script/GenericMovementSystem.EGMS_EffectsContextMatchType",NewName="/Script/GenericEffectsSystem.EGES_EffectsContextMatchType")
+EnumRedirects=(OldName="/Script/GenericMovementSystem.EGMS_ContextEffectsLibraryLoadState",NewName="/Script/GenericEffectsSystem.EGES_ContextEffectsLibraryLoadState")
+ClassRedirects=(OldName="/Script/GenericMovementSystem.GMS_ActiveContextEffects",NewName="/Script/GenericEffectsSystem.GES_ActiveContextEffects")
+ClassRedirects=(OldName="/Script/GenericMovementSystem.GMS_ContextEffectsLibrary",NewName="/Script/GenericEffectsSystem.GES_ContextEffectsLibrary")
+ClassRedirects=(OldName="/Script/GenericMovementSystem.GMS_ContextEffectsSettings",NewName="/Script/GenericEffectsSystem.GES_ContextEffectsSettings")
+ClassRedirects=(OldName="/Script/GenericMovementSystem.GMS_ContextEffectsSet",NewName="/Script/GenericEffectsSystem.GES_ContextEffectsSet")
+ClassRedirects=(OldName="/Script/GenericMovementSystem.GMS_ContextEffectsSubsystem",NewName="/Script/GenericEffectsSystem.GES_ContextEffectsSubsystem")
+ClassRedirects=(OldName="/Script/GenericMovementSystem.GMS_AnimNotify_ContextEffects",NewName="/Script/GenericEffectsSystem.GES_AnimNotify_ContextEffects")
+ClassRedirects=(OldName="/Script/GenericMovementSystem.GMS_ContextEffectComponent",NewName="/Script/GenericEffectsSystem.GES_ContextEffectComponent")
+ClassRedirects=(OldName="/Script/GenericMovementSystem.GMS_ContextEffectsInterface",NewName="/Script/GenericEffectsSystem.GES_ContextEffectsInterface")


;Content to plugins migrate
+ClassRedirects=(OldName="/Script/GenericEffectsSystem.GES_ContextEffectsPreview",NewName="/Script/GenericEffectsSystem.GES_ContextEffectsPreviewSetting")

